# Generated by Django 5.1.6 on 2025-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_alter_catagory_image_product_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Category',
        ),
    ]
